### PR TITLE
Additional cursor features by InsightCM

### PR DESCRIPTION
**Pull request by maxerdwien**

### CODE REVIEW

**Comment by cipix2000** [comment]
The changes look fine to me. However I'm reluctant to merge them in without tests. Can you please find a bit of time to add tests ?

**Comment by maxerdwien** [comment]
Today is my last day working for NI, but I should have time to add some tests.

**Comment by maxerdwien** [comment]
I added tests to my build to cover my new features. About half of the tests are unspecified, since I had limited time.

**Comment by cipix2000** [comment]
Thanks, I'll pull this when I'll have time to finish the tests.

**Pull request merged**
